theme: jekyll-theme-minimal
title: [Amherst College Data* Mammoths]
description: [A research and learning group on "everything data" (data mining,
  knowledge discovery, network science, machine learning, databases, …), led by
  Prof. Matteo Riondato]
logo: [img/acdmammoths.jpg]
